import pathlib
import re
import unittest


ROOT = pathlib.Path(__file__).resolve().parent
LOCK = ROOT / "requirements.lock"
SEMANTICA_SHA256 = "5bc33a5529aaa496dfdbca6d0bfc8301cb8f795b127e360d93ecb5b16a6a5fc0"


class LockFileTest(unittest.TestCase):
    def test_every_pinned_requirement_has_at_least_one_sha256(self):
        text = LOCK.read_text(encoding="utf-8")
        blocks = re.split(r"(?m)(?=^[A-Za-z0-9_.-]+==)", text)
        requirements = [block for block in blocks if re.match(r"^[A-Za-z0-9_.-]+==", block)]
        self.assertGreater(len(requirements), 100)
        for block in requirements:
            name = block.split("==", 1)[0]
            with self.subTest(requirement=name):
                self.assertRegex(block, r"--hash=sha256:[0-9a-f]{64}")

    def test_semantica_and_generation_environment_are_fixed(self):
        text = LOCK.read_text(encoding="utf-8")
        self.assertIn("autogenerated by pip-compile with Python 3.11", text)
        semantica = re.search(
            r"(?ms)^semantica==0\.6\.5 \\\n(?P<body>.*?)(?=^[A-Za-z0-9_.-]+==|\Z)",
            text,
        )
        self.assertIsNotNone(semantica)
        self.assertIn(f"--hash=sha256:{SEMANTICA_SHA256}", semantica.group("body"))
        expected_base = (
            "python:3.11.9-slim-bookworm@sha256:"
            "2856e6af199e8128161abd320575eb9b341f3b76f017b5d0c9cd364f60d8a050"
        )
        self.assertIn(expected_base, (ROOT / "Dockerfile").read_text(encoding="utf-8"))
        self.assertIn(
            expected_base,
            (ROOT / "cloudbuild.lock.yaml").read_text(encoding="utf-8"),
        )

    def test_lock_has_no_editable_or_remote_requirement(self):
        text = LOCK.read_text(encoding="utf-8")
        self.assertNotRegex(text, r"(?m)^\s*(?:-e|--editable)\s")
        self.assertNotRegex(text, r"(?m)^[A-Za-z0-9_.-]+\s*@\s*https?://")

    def test_build_requirements_are_pinned_for_hash_mode(self):
        text = LOCK.read_text(encoding="utf-8")
        self.assertRegex(text, r"(?m)^setuptools==[0-9]", "setuptools must be pinned")
        self.assertNotIn("packages were not pinned", text)


if __name__ == "__main__":
    unittest.main()
